name: covid
channels:
  - conda-forge
  - defaults
dependencies:
  - pexpect=4.8.0
  - libopenblas=0.3.12
  - nbclient=0.5.1
  - decorator=4.4.2
  - pyzmq=19.0.2
  - cffi=1.14.3
  - importlib_metadata=2.0.0
  - jsonschema=3.2.0
  - jupyterlab_pygments=0.1.2
  - pyparsing=2.4.7
  - markupsafe=1.1.1
  - nb_conda=2.2.1
  - terminado=0.9.1
  - async_generator=1.10
  - nb_conda_kernels=2.3.0
  - entrypoints=0.3
  - wcwidth=0.2.5
  - ipykernel=5.3.4
  - xz=5.2.5
  - attrs=20.2.0
  - python=3.6.12
  - nbformat=5.0.8
  - notebook=6.1.4
  - libffi=3.3
  - pip=20.2.4
  - jupyter_client=6.1.7
  - python-dateutil=2.8.1
  - libedit=3.1.20191231
  - openssl
  - zipp=3.3.1
  - testpath=0.4.4
  - libblas=3.9.0
  - jupyter_core=4.6.3
  - nbconvert=6.0.7
  - prometheus_client=0.8.0
  - zlib=1.2.11
  - pandocfilters=1.4.2
  - pandoc=2.11
  - llvm-openmp=11.0.0
  - tk=8.6.10
  - traitlets=4.3.3
  - defusedxml=0.6.0
  - jinja2=2.11.2
  - mistune=0.8.4
  - libcblas=3.9.0
  - nest-asyncio=1.4.1
  - ipython_genutils=0.2.0
  - setuptools=50.3.0
  - ca-certificates
  - bleach=3.2.1
  - joblib=0.17.0
  - libcxx=10.0.0
  - lightgbm=2.3.0
  - webencodings=0.5.1
  - certifi
  - ncurses=6.2
  - six=1.15.0
  - send2trash=1.5.0
  - readline=8.0
  - wheel=0.35.1
  - pyrsistent=0.17.3
  - pycparser=2.20
  - importlib-metadata=2.0.0
  - argon2-cffi=20.1.0
  - liblapack=3.9.0
  - packaging=20.4
  - tornado=6.0.4
  - jedi=0.17.2
  - backcall=0.2.0
  - libsodium=1.0.18
  - python_abi=3.6
  - zeromq=4.3.3
  - sqlite=3.33.0
  - shap
